<a id="topo"></a>
# Módulo 1 - python
> # Exercício de Condicionais

# Questões

>  - <a href="#expr">Avaliação de expressões</a>
>     - <a href="#outra_forma">Nota: Uma outra forma de escrever `and` e `or`</a>
>     - <a href="#conjuntos">Nota: Uma visão de conjuntos</a>
>  - <a href="#adv">Exercício avançado: Construção de condicionais</a>

## Avaliação de expressões <a id="expr" href="#topo">$\uparrow$</a>

> ### Instruções
> 
>  - Cada célula contém uma expressão condicional. Você deve avaliar se essa expressão retornará `True` ou `False`. 
>  - Faça isso em uma folha de papel antes de executá-la.
>  - As expressões estão ordenadas das mais simples para as mais complexas.
>  - Para as mais complexas, avalie cada expressão antes de avaliar os operadores lógicos `and` e `or`.

<hr />
<div style="float: left;">
    
### Operadores:
    
> | Operador | Significado    |
> |:--------:|:--------------:|
> |`>=`      | Maior ou igual |
> |`>`       | Maior          |
> |`==`      | Igual          |
> |`!=`      | Diferente      |
> |`<`       | Menor          |
> |`<=`      | Menor ou igual |
    
<br />
    
### Operadores lógicos
> #### and
> ``` python
> True  and True  == True
> True  and False == False
> False and True  == False
> False and False == False
> ```
>     
> #### or
> ``` python
> True  or True  == True
> True  or False == True
> False or True  == True
> False or False == False
> ```
</div>

In [ ]:
idade = 37

idade > 20

In [ ]:
idade = 42

idade >= 42

In [ ]:
idade = 28

idade > 28

In [ ]:
idade = 31

idade != 31

In [ ]:
idade = 42

(idade > 40) and (idade < 43)

In [ ]:
idade = 18

(idade > 15) or (idade < 20)

In [ ]:
idade = 18

(idade > 15) or (idade < 16)

In [ ]:
idade = 33

(idade < 30) and (idade > 32)

In [ ]:
idade = 40

(idade > 40) and (idade < 40)

In [ ]:
idade = 44

(idade < 20) or (idade == 44)

### Nota: Uma outra forma de escrever `and` e `or` <a href="#topo" id="outra_forma">$\uparrow$</a>

> - O operador `and` também pode ser escrito como `&`
> - O operador `or` também pode ser escrito como `|` (a tecla do lado do `Z` do seu teclado, pressionada com `Shift`)

In [ ]:
idade = 23

(idade > 20) & (idade < 30)

In [ ]:
idade = 49

(idade < 20) | (idade > 40)

### Nota: Uma visão de conjuntos <a href="#topo" id="conjuntos">$\uparrow$</a>

> O operador `and` pode ser visto como **INSTERSECÇÃO** de conjuntos:

> #### Exemplo visual 1: `(Idade>20) & (idade<40)` <br/>
> <div style="width:50%;">
> <img src="img/g1.png" /><br/>
> <code style="text-align: center; display: block">AND</code>
> <img src="img/l2.png" /><br/>
> <code style="text-align: center; display: block">==</code>
> <img src="img/union_in.png" />
> </div>

<hr/>

> #### Exemplo visual 2: `(Idade>40) & (idade<20)` <br/>
> <div style="width:50%;">
> <img src="img/g2.png" /><br/>
> <code style="text-align: center; display: block">AND</code>
> <img src="img/l1.png" /><br/>
> <code style="text-align: center; display: block">==</code>
> <img src="img/empty.png" />
> </div>

<hr />
<hr />

> Já o operador `or` pode ser visto como **UNIÃO** de conjuntos:

> #### Exemplo visual 3: `(Idade>20) | (idade<40)` <br/>
> <div style="width:50%;">
> <img src="img/g1.png" /><br/>
> <code style="text-align: center; display: block">OR</code>
> <img src="img/l2.png" /><br/>
> <code style="text-align: center; display: block">==</code>
> <img src="img/all.png" />
> </div>

<hr/>

> #### Exemplo visual 4: `(Idade>40) | (idade<20)` <br/>
> <div style="width:50%;">
> <img src="img/g2.png" /><br/>
> <code style="text-align: center; display: block">OR</code>
> <img src="img/l1.png" /><br/>
> <code style="text-align: center; display: block">==</code>
> <img src="img/union_out.png" />
> </div>

In [ ]:
idade = 40
salario = 7000

(idade > 20) and (salario < 10000)

In [ ]:
idade = 20
salario = 13000

(idade > 18) and (salario > 10000) and (salario < 15000)

In [ ]:
idade = 45
salario = 10000

((idade < 40) or (idade > 60)) and (salario > 7000)

In [ ]:
idade = 38
salario = 9000

((idade >30) and (idade < 40)) or (salario < 5000)

In [ ]:
idade = 26
salario = 8000

((idade < 30) | (idade > 60)) & ((salario > 12000) | (salario < 9000))

## Exercício avançado: Construção de condicionais <a href="#topo" id="adv">$\uparrow$</a>

> ### Instruções
> 
>  - Para este exercício, utilizaremos a biblioteca `numpy`. Você não precisará utilizá-la diretamente, mas ela será utilizada para que você possa corrigir seu exercício
>  - Antes de começar o exercício, execute a célula abaixo para criar as variaveis `idade`, `salario`
>  - Cada célula contém um comentário (Texto após o caracter `#`) descrevendo uma situação que deve ser resolvida criando uma condicional
>  - Você deve criar a sua condição na variável `cond`, e depois executar a célula para verificar se sua condição está correta.

> Abaixo há um exemplo executado para que você possa se guiar. Você deve colocar sua condição na área marcada em amarelo
<div style="background-color: #eeeeee; padding: 20px;">
    
<code style="background-color: #eeeeee">
# Selecione os funcionários com mais de 30 anos
<p style="background-color: #ffff00">cond = idade>30</p>

resp = np.array([ True, False, False, False, False,  True,  True,  True,  True,
        True,  True, False,  True, False, False, False,  True, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True, False,  True,  True, False,  True,
        True, False,  True, False, False,  True,  True, False,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False, False, False,  True,  True, False,  True,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
        True, False,  True, False,  True, False, False,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
        True,  True,  True,  True,  True, False, False, False,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
        True, False, False, False,  True,  True,  True, False,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False, False,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False, False,  True, False, False,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True, False,
       False,  True,  True,  True, False, False,  True, False,  True,
        True,  True, False,  True,  True, False,  True, False, False,
        True,  True])

if np.all(cond==resp):
    print("""
Sua resposta está certa! \o/
""")
else:
    print("""
Você errou :'(
Mas não desanime! Caso tenha dúvidas, poste na comunidade de alunos: https://www.facebook.com/groups/121036129888085
,ou no e-mail alunos@rafinhadosdados.com.br
    """)
    </code>
    
</div>

In [ ]:
### EXECUTE ESSA CÉLULA ANTES DO EXERCÍCIO!

import numpy as np
idade = np.array([70,  9, 17, 12, 19, 58, 60, 45, 69, 39, 63, 11, 48, 16, 27, 14, 55,
       16, 49, 51, 75,  6, 43, 44, 78, 39, 20, 41, 21, 19, 48, 14, 76, 67,
       17, 59, 36, 12, 49,  9, 26, 40, 75, 21, 65, 10, 73, 47, 39, 55,  0,
       46, 31,  7, 40, 31, 47, 56,  1,  9, 68, 44, 52, 69, 29, 10, 25, 76,
       76,  1, 66, 69, 69, 43, 54, 53,  3, 11, 31, 11, 35, 67, 25, 53,  0,
       40, 26, 14, 41, 52, 50, 68, 35,  1, 53, 29, 39, 67, 33, 44, 41, 38,
       18,  2, 66, 36, 34,  7, 56, 58, 78, 75, 65,  3, 21,  0, 74, 41,  9,
       50, 35, 31, 29, 33, 14, 36, 60, 10, 23, 30, 69, 37, 36, 13, 31, 61,
       11, 39, 47,  2, 16, 37, 64, 45, 53, 77, 33, 12, 63, 62, 45, 26, 20,
       61, 29, 69, 37,  4, 41, 75, 35, 36, 10, 27, 67,  5, 29, 65, 38, 33,
       52, 65, 49, 70, 28, 56, 23, 63, 78, 24, 19, 52, 69, 79, 11, 18, 46,
       26, 66, 54, 62, 28, 49, 66, 23, 32, 28, 28, 79, 32])

salario = np.array([15000, 12000,  9000, 27000,  5000, 11000, 10000, 18000, 22000,
       17000, 29000, 24000, 23000, 14000, 10000, 17000,  8000, 11000,
       13000, 17000, 16000,  8000, 10000, 29000, 23000, 10000, 29000,
       20000, 14000, 24000, 11000, 28000, 17000, 29000, 19000, 22000,
       20000,  6000, 16000, 23000, 17000, 12000,  6000,  7000, 12000,
        5000,  6000, 19000, 10000, 11000, 11000, 26000, 21000, 21000,
       28000, 19000,  7000,  5000, 20000,  9000, 17000, 11000, 22000,
       17000, 26000,  7000, 27000, 13000, 25000, 28000,  9000,  8000,
       13000, 13000, 24000,  6000, 11000,  9000, 24000, 19000,  8000,
       19000,  8000, 29000, 24000, 21000, 22000, 14000, 26000, 16000,
       11000, 22000, 15000, 26000, 18000, 29000,  6000, 10000, 14000,
       10000, 14000, 25000, 15000, 26000, 29000,  9000, 13000, 10000,
       10000, 24000, 13000,  8000,  8000, 10000, 10000, 23000,  9000,
       29000, 18000, 22000, 11000, 26000,  7000, 12000, 22000, 26000,
       25000, 21000, 18000,  9000,  8000, 25000, 23000, 13000, 19000,
        7000, 24000, 23000, 23000, 15000, 26000, 12000, 24000, 20000,
       29000, 25000, 26000, 15000,  6000, 20000, 21000, 27000,  8000,
       15000, 27000,  5000,  7000,  6000, 15000, 14000, 24000, 26000,
       16000, 25000,  8000, 20000, 10000,  6000, 13000, 26000, 22000,
       25000, 26000, 20000, 25000, 10000, 15000, 11000, 28000,  5000,
       25000, 12000,  5000, 27000, 27000, 20000, 25000,  7000, 19000,
        6000, 18000, 26000, 12000, 12000, 19000, 22000, 24000, 18000,
       16000, 24000])

In [ ]:
# Selecione os funcionários com mais de 30 anos (sem contar os de 30)
cond = 

resp = np.array([ True, False, False, False, False,  True,  True,  True,  True,
        True,  True, False,  True, False, False, False,  True, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True, False,  True,  True, False,  True,
        True, False,  True, False, False,  True,  True, False,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True, False, False, False,  True,  True, False,  True,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
        True, False,  True, False,  True, False, False,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True, False,
        True,  True,  True,  True,  True, False, False, False,  True,
        True, False,  True,  True,  True, False,  True, False,  True,
        True, False, False, False,  True,  True,  True, False,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False, False,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False, False,  True, False, False,  True,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True, False,
       False,  True,  True,  True, False, False,  True, False,  True,
        True,  True, False,  True,  True, False,  True, False, False,
        True,  True])

if np.all(cond==resp):
    print("""
Sua resposta está certa! \o/
""")
else:
    print("""
Você errou :'(
Mas não desanime! Tente refazer! 
Caso tenha dúvidas, poste na comunidade de alunos: https://www.facebook.com/groups/121036129888085
,ou no e-mail alunos@rafinhadosdados.com.br
    """)

In [ ]:
# Selecione os funcionários que recebem menos ou igual a 7000
cond = 

resp = np.array([ False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False,  True,  True, False,
        True,  True, False, False, False, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False, False,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False])

if np.all(cond==resp):
    print("""
Sua resposta está certa! \o/
""")
else:
    print("""
Você errou :'(
Mas não desanime! Tente refazer! 
Caso tenha dúvidas, poste na comunidade de alunos: https://www.facebook.com/groups/121036129888085
,ou no e-mail alunos@rafinhadosdados.com.br
    """)

In [ ]:
# Selecione os funcionários que recebem entre 7000 e 12000 reais, incluindo as "bordas"
cond = 

resp = np.array([False,  True,  True, False, False,  True,  True, False, False,
       False, False, False, False, False,  True, False,  True,  True,
       False, False, False,  True,  True, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
       False, False, False,  True,  True,  True, False, False, False,
       False, False,  True, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False,  True,  True,
       False, False, False, False,  True,  True, False, False,  True,
       False,  True, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
        True, False, False, False, False, False,  True, False,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
       False, False, False,  True, False,  True,  True, False, False,
       False, False, False,  True,  True, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False])

if np.all(cond==resp):
    print("""
Sua resposta está certa! \o/
""")
else:
    print("""
Você errou :'(
Mas não desanime! Tente refazer! 
Caso tenha dúvidas, poste na comunidade de alunos: https://www.facebook.com/groups/121036129888085
,ou no e-mail alunos@rafinhadosdados.com.br
    """)

In [ ]:
# Selecione os funcionários com salario inferior a 8000 e idade superior a 50 (incluindo as "bordas")
cond = 

resp = np.array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False])

if np.all(cond==resp):
    print("""
Sua resposta está certa! \o/
""")
else:
    print("""
Você errou :'(
Mas não desanime! Tente refazer! 
Caso tenha dúvidas, poste na comunidade de alunos: https://www.facebook.com/groups/121036129888085
,ou no e-mail alunos@rafinhadosdados.com.br
    """)

In [ ]:
# Dos funcionários com menos de 30 anos, selecione os que ganham menos de 8000, contando as "bordas"
# Dos funcionáros com mais de 50 anos, selecione os que ganham mais de 15000, contando as "bordas"
cond = 

resp = np.array([ True, False, False, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False, False, False,
       False,  True,  True,  True, False, False,  True, False, False,
       False, False, False, False, False,  True,  True, False,  True,
       False,  True, False, False, False, False, False,  True, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
        True, False,  True, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True,  True,  True, False, False, False, False, False,  True,
       False,  True, False, False,  True, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
        True,  True, False, False, False,  True, False, False,  True,
        True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True, False,  True, False, False, False, False,  True,  True,
       False, False, False,  True, False, False, False,  True,  True,
       False,  True, False, False, False, False, False, False, False,
        True, False])

if np.all(cond==resp):
    print("""
Sua resposta está certa! \o/
""")
else:
    print("""
Você errou :'(
Mas não desanime! Tente refazer! 
Caso tenha dúvidas, poste na comunidade de alunos: https://www.facebook.com/groups/121036129888085
,ou no e-mail alunos@rafinhadosdados.com.br
    """)

In [ ]:
# Selecione os funcionários com idade entre 30 e 50 anos, e salario entre 6000 e 10000, sempre incluindo as bordas
cond = 

resp = np.array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

if np.all(cond==resp):
    print("""
Sua resposta está certa! \o/
""")
else:
    print("""
Você errou :'(
Mas não desanime! Tente refazer! 
Caso tenha dúvidas, poste na comunidade de alunos: https://www.facebook.com/groups/121036129888085
,ou no e-mail alunos@rafinhadosdados.com.br
    """)